name: Build
on:
  workflow_call:
    inputs:
      rev:
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.rev }}

      - run: echo sha="$(git rev-parse ${{ inputs.rev }})" >> $GITHUB_ENV
      
      - uses: LouisBrunner/checks-action@v2.0.0
        id: init
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Build
          sha: ${{ env.sha }}
          status: in_progress

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build
        run: nix build -L

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.rev }}-vmlinux
          path: result/vmlinux
      
      - uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.init.outputs.check_id }}
          conclusion: ${{ job.status }}
